---
- name: Create directories for godc
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: "0755"
  loop:
    - "{{ gocd_deploy_dir }}"
    - "{{ gocd_data_dir }}"
    - "{{ gocd_home_dir }}"
  become: true

- name: Render gocd docker-compose
  template:
    src: "docker-compose.yml"
    dest: "{{ gocd_deploy_dir }}/docker-compose.yml"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    mode: "0644"
  become: true

